[package]
name = "vault-local-platform-windows"
version = "0.0.1-alpha.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_UI_Shell",
] }
